cmake_minimum_required(VERSION 3.25)
project(odev3)

set(CMAKE_CXX_STANDARD 17)

add_executable(odev3 main.cpp Elements.cpp Elements.h Food.cpp Food.h Wood.cpp Wood.h MedicalSupplies.cpp MedicalSupplies.h Gold.cpp Gold.h Wild.cpp Wild.h  Wolf.cpp Wolf.h Bear.cpp Bear.h Player.cpp Player.h Grid_Class.cpp Grid_Class.h)
